site_name: Echo Speaks Documentation
site_url: https://tonesto7.github.io/echo-speaks-docs
repo_url: https://github.com/tonesto7/echo-speaks
edit_uri: ""
site_description: Echo Speaks Documentation
# use_directory_urls: False
remote_branch: gh-pages
remote_name: origin
google_analytics: ["UA-131811674-1", "tonesto7.github.io/echo-speaks-docs"]

theme:
  name: material
  features:
    - tabs
    - instant
  icon:
    repo: fontawesome/brands/github
  extra:
    social:
      - icon: fontawesome/brands/github-alt
        link: https://github.com/tonesto7/echo-speaks
  highlightjs: true
  hljs_languages:
    - yaml
    - rust
  palette:
    primary: "blue"
    accent: "blue"

nav:
  - Home: index.md
  - Install:
      - 'Select Platform':
        - Hubitat: installation/hubitat/installs.md
        - SmartThings: installation/smartthings/installs.md

  - Configuration:
      - Hubitat:
          - App: configuration/hubitat/config_app.md
          - Server: configuration/hubitat/config_server.md
      - SmartThings:
          - App: configuration/smartthings/config_app.md
          - Server: configuration/smartthings/config_server.md

  - Updates:
      - Hubitat:
          - App: updates/hubitat/app_update.md
          - Device: updates/hubitat/device_update.md
      - SmartThings:
          - App: updates/smartthings/app_update.md
          - Device: updates/smartthings/device_update.md
      - Server: updates/server_update.md

  - Actions:
      - Description: actions/actions_desc.md
      - Configuration: actions/config/actions_config.md
      - Examples: actions/examples/actions_examples.md

  - Support:
      - Server Removal/Reset: support/server_removal.md
      - Supported Devices: devicesupport/supported_devices.md
      - Common Errors: support/common_errors.md
      - Reporting Issues: support/reporting_issues.md
      - F.A.Q.: faq.md

  - Device API:
    - Device Attributes: devicesupport/device_attributes.md
    - Device Commands:
      - General: devicesupport/commands/action_commands.md
      - Alerts | Notifications: devicesupport/commands/alerts_commands.md
      - Music: devicesupport/commands/music_commands.md
      - Speech: devicesupport/commands/speech_commands.md

  - Donate: donations.md

markdown_extensions:
  - smarty
  - meta
  - sane_lists
  - toc:
      permalink: "#"
      baselevel: 2
      separator: "_"
  - codehilite

plugins:
  - search:
      prebuild_index: true
  - autolinks
  - awesome-pages
  - git-revision-date-localized:
      type: timeago
  - minify:
      minify_html: true
  # - mdoctag
  # - bootstrap-tables


extra_css:
  - "css/extra.css"

extra_javascript:
  - "js/extra.js"
